# O que é PyTorch?

É um pacote de computação científica com base em Python com dois objetivos:
* um substituto do NumPy para usar o pder das GPUs;
* uma plataforma de pesquisa em _Deep Learning_ que fornece máxima flexibilidade e velocidade.

## Primeiro contato

Testando se este foi instalado corretamente.

In [28]:
# importing libs
from __future__ import print_function
import torch
torch.cuda.is_available()

True

## Tensores

Tensores são semelhantes aos `ndarrays` do NumPy, com a diferença de que Tensores podem também ser usados em uma GPU para acelerar a computação.

> Uma matriz não-inicializada é declarada, mas não contém valores definitivos conhecidos antes de serem usados. Quando uma matris não-inicializada é criada, qualquer valor que estavam alocados na memória no momento aparecerá como valores iniciais.

Construção de uma matriz 5.3, não-inicializada:

In [29]:
x = torch.empty(5,3)
print(x)

tensor([[1.3765e+22, 4.5664e-41, 1.3765e+22],
        [4.5664e-41, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 7.7052e+31, 7.2148e+22],
        [2.5226e-18, 6.4825e-10, 1.0299e-11]])


Construção de uma matriz inicializada aleatoriamente:

In [30]:
x = torch.rand(5,3)
print(x)

tensor([[0.4049, 0.5429, 0.1121],
        [0.8149, 0.2919, 0.8323],
        [0.8631, 0.2860, 0.0460],
        [0.0833, 0.3379, 0.1456],
        [0.6450, 0.3340, 0.6962]])


Construção de uma matriz preenchida de zeros e de dtype long:

In [31]:
x = torch.zeros(5,3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construção de um tensor diretamente de dados:

In [32]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


Criação de tensores baseados em um tensor existente. Estes métodos reutilizarão propriedades do tensor de input, e.g. dtype, a não ser que novos valores são fornecidos pelo usuário.

In [33]:
x = x.new_ones(5, 3, dtype=torch.double)    # métodos new_* requer dimensões (sizes).
print(x)

x = torch.randn_like(x, dtype=torch.float)  # sobrescreve dtype!
print(x)                                    # resultado tem a mesma dimensão.

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.0097,  1.6194,  1.1224],
        [ 0.8142, -1.2774, -2.1720],
        [-0.4947,  1.1750,  0.1962],
        [ 0.7895, -0.5454,  1.7313],
        [-0.8729, -0.4750,  0.3006]])


Consultar seu tamanho.
> `torch.size` retorna uma tupla, então esta suporta todas operações de tuplas.

In [34]:
x.size()

torch.Size([5, 3])

## Operações

Há múltiplas sintaxes para operações. Nos exemplos a seguir, veremos a operação de adição de tensores.

Adição: sintaxe 1

In [35]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.8763,  2.3513,  1.5427],
        [ 1.3611, -0.8185, -1.9195],
        [ 0.1033,  1.9678,  0.5241],
        [ 1.7448, -0.0498,  1.9301],
        [-0.2794,  0.2353,  0.9120]])


Adição: sintaxe 2

In [36]:
print(torch.add(x, y))

tensor([[ 0.8763,  2.3513,  1.5427],
        [ 1.3611, -0.8185, -1.9195],
        [ 0.1033,  1.9678,  0.5241],
        [ 1.7448, -0.0498,  1.9301],
        [-0.2794,  0.2353,  0.9120]])


Adição: fornecendo um tensor output como argumento.

In [37]:
result = torch.empty(5,3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.8763,  2.3513,  1.5427],
        [ 1.3611, -0.8185, -1.9195],
        [ 0.1033,  1.9678,  0.5241],
        [ 1.7448, -0.0498,  1.9301],
        [-0.2794,  0.2353,  0.9120]])


Adição: _in-place_.
> Qualquer operação que modifique um tensor _in-place_ é pós-fixado com um `_`. Por exemplo: `x.copy_(y)`, `x.t_()`, mudarão `x`.

In [38]:
# adiciona x ao y
y.add_(x)
print(y)

tensor([[ 0.8763,  2.3513,  1.5427],
        [ 1.3611, -0.8185, -1.9195],
        [ 0.1033,  1.9678,  0.5241],
        [ 1.7448, -0.0498,  1.9301],
        [-0.2794,  0.2353,  0.9120]])


Pode-se utilizar indexação padrão da biblioteca NumPy em tensores!

In [39]:
print(x[:, 1])

tensor([ 1.6194, -1.2774,  1.1750, -0.5454, -0.4750])


Redimensionamento: Se quiser redimensionar um tensor, podemos utilizar `torch.view`:

In [40]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)      # a dimensão -1 é inferida da outra dimensão conhecida.
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


Se tiver um tensor de dimensão 1, use `.item()` para pegar o valor como um número Python.

In [41]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.0167])
-1.016679286956787


## NumPy Bridge

Convertendo um Tensor Torch em um _array_ NumPy e vice-versa é simples.

O Tensor Torch e _array_ NumPy compartilharão os locais de memória subjacentes (se o Tensor Torch estiver na CPU), então alterando um alterará o outro.

### Convertendo um Tensor Torch em um _Array_ NumPy

In [42]:
a = torch.ones(5)
print(a)

b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


Observe como o _array_ numpy também altera o valor.

In [43]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### Convertendo um _Array_ NumPy em um Tensor Torch

Observe como alterar um _array_ numpy altera o Tensor Torch automaticamente.

In [44]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


Todos os Tensores na CPU podem ser convertidos em NumPy e vice-versa, exceto _CharTensor_. 

## Tensores CUDA

Tensores podem ser movidos sobre qualquer dispositivo usando o método `.to`.

In [45]:
# executaremos esta célula apenas se CUDA estiver disponível.
# Usaremos objetos ``torch.device`` para mover tensores para/do GPU.
if (torch.cuda.is_available()):
    device = torch.device("cuda")         # um objetdo de dispositivo CUDA.
    y = torch.ones_like(x, device=device) # cria um tensor no GPU diretamente.
    x = x.to(device)                      # ou apenas use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))      # ``.to`` pode também alterar o dtype junto!

tensor([-0.0167], device='cuda:0')
tensor([-0.0167], dtype=torch.float64)


> Referência: [WHAT IS PYTORCH?](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py)